### ISSUE TITLE
Could not find concurrent-ruby-1.0.5 in any of the sources

### ISSUE THREAD

**Issue by hparfr** [akretion/shopinvader#19]
In v3.4.x branch,
```sh
$ gosu loco bundle exec puma -C config/puma.rb
 Could not find concurrent-ruby-1.0.5 in any of the sources
```
I had to : 
* install git 
* mount /usr/local/bundle
* bundle install

**Comment by sebastienbeau** [comment]
as seen in your case the issue was in your docker configuration, you should not mount the /usr/local/bundle
