### ISSUE TITLE
Case insensitive searches

### ISSUE THREAD

**Issue by JordiBForgeFlow** [akretion/shopinvader#66]
How can we achieve case insensitive searches in Shopinvader?

So, a user typing "table" in the search bar will produce the same result as typing "Table".

I can see that this works fine in the demo store https://default.site.demo.shopinvader.com/?q=table
![image](https://user-images.githubusercontent.com/7683926/101808766-08a13000-3b17-11eb-8155-5501a84b26ef.png)

I believe that this must be a setting in ElasticSearch?¿

@hviorforgeflow

**Comment by rousseldenis** [comment]
> How can we achieve case insensitive searches in Shopinvader?
> 
> So, a user typing "table" in the search bar will produce the same result as typing "Table".
> 
> I can see that this works fine in the demo store https://default.site.demo.shopinvader.com/?q=table
> ![image](https://user-images.githubusercontent.com/7683926/101808766-08a13000-3b17-11eb-8155-5501a84b26ef.png)
> 
> I believe that this must be a setting in ElasticSearch?¿
> 
> @HviorForgeFlow

I think this is a setting for the index key. I can investiguate.
